recette_recette:
    resource: "@RecetteBundle/Controller/RecetteController.php"
    type:     annotation

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /

recette:
    resource: "@RecetteBundle/Controller/"
    type:     annotation
    prefix:   /

securite:
    resource: "@SecuriteBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
