# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        SecuriteBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                #providers: [ in_memory, db_provider ]
                providers: [ in_memory, db_provider ]
        in_memory:
            memory: 
                users:
                    admin:
                        password: $2y$13$vbonEYxHT6T9iSF1ePGQ3uwDMXJ7L7DSQsnqKiyjad6mDpA1yaQHq
                        roles: 'ROLE_ADMIN'

        db_provider:
            entity:
                class: SecuriteBundle:User
                #Sproperty: username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            pattern: ^/
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   logout
                target: homepage
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/dashboard, role: IS_AUTHENTICATED_FULLY}

