<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYlehgya\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYlehgya/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYlehgya.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYlehgya\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYlehgya\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ylehgya',
    'container.build_id' => '90b58d19',
    'container.build_time' => 1526858799,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYlehgya');
