<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFgxt6vi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFgxt6vi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFgxt6vi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFgxt6vi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFgxt6vi\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fgxt6vi',
    'container.build_id' => '7a87aafe',
    'container.build_time' => 1528055160,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFgxt6vi');
