<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQjygzfl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQjygzfl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQjygzfl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQjygzfl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQjygzfl\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Qjygzfl',
    'container.build_id' => '6539ae80',
    'container.build_time' => 1526846733,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQjygzfl');
